-- Insert 75 demo problem statements
INSERT INTO problem_statements (title, description, selected_teams_count, created_date) VALUES 
('Problem Statement 1', 'Build a smart home automation system', 0, NOW()),
('Problem Statement 2', 'Create an AI-powered chatbot for customer support', 0, NOW()),
('Problem Statement 3', 'Develop a real-time traffic management system', 0, NOW()),
('Problem Statement 4', 'Design a mobile health monitoring app', 0, NOW()),
('Problem Statement 5', 'Build a blockchain-based supply chain tracker', 0, NOW()),
('Problem Statement 6', 'Create an augmented reality shopping experience', 0, NOW()),
('Problem Statement 7', 'Develop a machine learning model for disease prediction', 0, NOW()),
('Problem Statement 8', 'Design a gamified learning platform', 0, NOW()),
('Problem Statement 9', 'Build a real-time collaborative coding environment', 0, NOW()),
('Problem Statement 10', 'Create a sustainable waste management solution', 0, NOW()),
('Problem Statement 11', 'Develop a voice-activated home assistant', 0, NOW()),
('Problem Statement 12', 'Design an IoT sensor network for agriculture', 0, NOW()),
('Problem Statement 13', 'Build a cybersecurity threat detection system', 0, NOW()),
('Problem Statement 14', 'Create an automated resume screening tool', 0, NOW()),
('Problem Statement 15', 'Develop a virtual reality training simulator', 0, NOW()),
('Problem Statement 16', 'Design a smart energy management system', 0, NOW()),
('Problem Statement 17', 'Build a community disaster response platform', 0, NOW()),
('Problem Statement 18', 'Create an AI image recognition system', 0, NOW()),
('Problem Statement 19', 'Develop a personalized nutrition planning app', 0, NOW()),
('Problem Statement 20', 'Design a quantum computing simulator', 0, NOW()),
('Problem Statement 21', 'Build a federated learning framework', 0, NOW()),
('Problem Statement 22', 'Create a digital currency wallet system', 0, NOW()),
('Problem Statement 23', 'Develop a predictive maintenance system', 0, NOW()),
('Problem Statement 24', 'Design an intelligent traffic signal control', 0, NOW()),
('Problem Statement 25', 'Build a cloud-based document collaboration tool', 0, NOW()),
('Problem Statement 26', 'Create a sentiment analysis social media tool', 0, NOW()),
('Problem Statement 27', 'Develop a facial recognition security system', 0, NOW()),
('Problem Statement 28', 'Design a smart water management system', 0, NOW()),
('Problem Statement 29', 'Build an automated financial advisory system', 0, NOW()),
('Problem Statement 30', 'Create a 3D environment mapping application', 0, NOW()),
('Problem Statement 31', 'Develop a language translation AI model', 0, NOW()),
('Problem Statement 32', 'Design a biometric authentication system', 0, NOW()),
('Problem Statement 33', 'Build a wildlife conservation monitoring platform', 0, NOW()),
('Problem Statement 34', 'Create a mental health support chatbot', 0, NOW()),
('Problem Statement 35', 'Develop a drone delivery optimization system', 0, NOW()),
('Problem Statement 36', 'Design an earthquake early warning system', 0, NOW()),
('Problem Statement 37', 'Build a career path recommendation engine', 0, NOW()),
('Problem Statement 38', 'Create a smart classroom attendance system', 0, NOW()),
('Problem Statement 39', 'Develop an accessibility tool for visually impaired', 0, NOW()),
('Problem Statement 40', 'Design a pandemic simulation and prediction model', 0, NOW()),
('Problem Statement 41', 'Build a renewable energy optimization platform', 0, NOW()),
('Problem Statement 42', 'Create a crowdsourced pollution monitoring system', 0, NOW()),
('Problem Statement 43', 'Develop a music recommendation algorithm', 0, NOW()),
('Problem Statement 44', 'Design a smart logistics routing system', 0, NOW()),
('Problem Statement 45', 'Build an automated crop disease detection system', 0, NOW()),
('Problem Statement 46', 'Create a cybersecurity incident response tool', 0, NOW()),
('Problem Statement 47', 'Develop a personalized fitness coaching app', 0, NOW()),
('Problem Statement 48', 'Design an urban air quality monitoring network', 0, NOW()),
('Problem Statement 49', 'Build a video content recommendation system', 0, NOW()),
('Problem Statement 50', 'Create a smart building occupancy management', 0, NOW()),
('Problem Statement 51', 'Develop a real-time sign language translator', 0, NOW()),
('Problem Statement 52', 'Design a financial fraud detection system', 0, NOW()),
('Problem Statement 53', 'Build a virtual event management platform', 0, NOW()),
('Problem Statement 54', 'Create an AI-powered drug discovery system', 0, NOW()),
('Problem Statement 55', 'Develop a smart irrigation scheduling system', 0, NOW()),
('Problem Statement 56', 'Design a public transportation optimization tool', 0, NOW()),
('Problem Statement 57', 'Build a document digitization and OCR system', 0, NOW()),
('Problem Statement 58', 'Create a skill gap analysis platform', 0, NOW()),
('Problem Statement 59', 'Develop a climate change impact simulator', 0, NOW()),
('Problem Statement 60', 'Design an adaptive learning assessment system', 0, NOW()),
('Problem Statement 61', 'Build a smart retail inventory management', 0, NOW()),
('Problem Statement 62', 'Create a content moderation AI system', 0, NOW()),
('Problem Statement 63', 'Develop a vehicle maintenance prediction system', 0, NOW()),
('Problem Statement 64', 'Design a social isolation detection system', 0, NOW()),
('Problem Statement 65', 'Build a news credibility verification tool', 0, NOW()),
('Problem Statement 66', 'Create a resource allocation optimization system', 0, NOW()),
('Problem Statement 67', 'Develop an autonomous parking management system', 0, NOW()),
('Problem Statement 68', 'Design a medical imaging analysis tool', 0, NOW()),
('Problem Statement 69', 'Build a customer lifetime value prediction model', 0, NOW()),
('Problem Statement 70', 'Create a maritime safety monitoring system', 0, NOW()),
('Problem Statement 71', 'Develop an intelligent email classification system', 0, NOW()),
('Problem Statement 72', 'Design a supply demand forecasting tool', 0, NOW()),
('Problem Statement 73', 'Build a sports analytics prediction engine', 0, NOW()),
('Problem Statement 74', 'Create an industrial equipment monitoring system', 0, NOW()),
('Problem Statement 75', 'Develop a user behavior analytics platform', 0, NOW());
